docker_image: &docker_image
  docker:
    - image: docker:19.03.6

version: 2
jobs:
  publish_drone_24:
    <<: *docker_image
    working_directory: ~/scriptjar
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          TAG=2.4-alpine
          docker build -t devatherock/drone-groovy-script-to-jar:$TAG -f docker/2.4-alpine/Drone.Dockerfile .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push devatherock/drone-groovy-script-to-jar:$TAG
  publish_drone_25:
    <<: *docker_image
    working_directory: ~/scriptjar
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          TAG=2.5-alpine
          docker build -t devatherock/drone-groovy-script-to-jar:$TAG -f docker/2.5-alpine/Drone.Dockerfile .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push devatherock/drone-groovy-script-to-jar:$TAG
  publish_vela_24:
    <<: *docker_image
    working_directory: ~/scriptjar
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          TAG=2.4-alpine
          docker build -t devatherock/vela-groovy-script-to-jar:$TAG -f docker/2.4-alpine/Vela.Dockerfile .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push devatherock/vela-groovy-script-to-jar:$TAG
  publish_vela_25:
    <<: *docker_image
    working_directory: ~/scriptjar
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          TAG=2.5-alpine
          docker build -t devatherock/vela-groovy-script-to-jar:$TAG -f docker/2.5-alpine/Vela.Dockerfile .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push devatherock/vela-groovy-script-to-jar:$TAG
  docker_build_dry_run_drone_24:
    <<: *docker_image
    working_directory: ~/scriptjar
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -f docker/2.4-alpine/Drone.Dockerfile .
  docker_build_dry_run_drone_25:
    <<: *docker_image
    working_directory: ~/scriptjar
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -f docker/2.5-alpine/Drone.Dockerfile .
  docker_build_dry_run_vela_24:
    <<: *docker_image
    working_directory: ~/scriptjar
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -f docker/2.4-alpine/Vela.Dockerfile .
  docker_build_dry_run_vela_25:
    <<: *docker_image
    working_directory: ~/scriptjar
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -f docker/2.5-alpine/Vela.Dockerfile .

workflows:
  version: 2
  docker_publish:
    jobs:
      - publish_drone_24:
          filters:
            branches:
              only: master
      - publish_drone_25:
          filters:
            branches:
              only: master
      - publish_vela_24:
          filters:
            branches:
              only: master
      - publish_vela_25:
          filters:
            branches:
              only: master
  pr_check:
    jobs:
      - docker_build_dry_run_drone_24:
          filters:
            branches:
              ignore: master
      - docker_build_dry_run_drone_25:
          filters:
            branches:
              ignore: master
      - docker_build_dry_run_vela_24:
          filters:
            branches:
              ignore: master
      - docker_build_dry_run_vela_25:
          filters:
            branches:
              ignore: master