version: 2
jobs:
  publish:
    docker:
    - image: docker:17.06.2-ce
    working_directory: ~/scriptjar
    steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true
    - run: |
        TAG=2.4-alpine
        docker build -t devatherock/drone-groovy-script-to-jar:$TAG -f 2.4-alpine/Dockerfile .
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker push devatherock/drone-groovy-script-to-jar:$TAG

workflows:
  version: 2
  docker-publish:
    jobs:
    - publish:
        filters:
          branches:
            only: master