version: 2
jobs:
  publish:
    docker:
      - image: docker:17.12.1-ce
    working_directory: ~/scriptjar
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          TAG=2.4-alpine
          docker build -t devatherock/drone-groovy-script-to-jar:$TAG -f 2.4-alpine/Dockerfile .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push devatherock/drone-groovy-script-to-jar:$TAG
  docker_build_dry_run:
    docker:
      - image: docker:17.12.1-ce
    working_directory: ~/scriptjar
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker build -f 2.4-alpine/Dockerfile .          

workflows:
  version: 2
  docker_publish:
    jobs:
      - publish:
          filters:
            branches:
              only: master
  pr_check:
    jobs:
      - docker_build_dry_run:
          filters:
            branches:
              ignore: master          